import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system colors
        background: '#F8FAFC',
        surface: '#F8FAFC',
        'surface-container': '#EAEDFF',
        'surface-container-high': '#E2E7FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F2F3FF',
        'on-surface': '#131B2E',
        'on-surface-variant': '#434655',
        primary: '#004AC6',
        'primary-container': '#2563EB',
        secondary: '#712AE2',
        'secondary-container': '#8A4CFC',
        outline: '#737686',
        'outline-variant': '#C3C6D7',
        error: '#BA1A1A',
        // Existing colors
        navy: {
          900: '#020617',
          800: '#0F172A',
          700: '#1E293B',
        },
        accent: {
          DEFAULT: '#7C3AED',
          50: '#F5F3FF',
          100: '#EDE9FE',
          500: '#7C3AED',
          600: '#6D28D9',
        },
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#EF4444',
        slate: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
        vault: {
          50: '#f8f7f4',
          100: '#f0efe9',
          200: '#e4e1d6',
          300: '#c8c4b4',
          400: '#a8a38c',
          500: '#8a8468',
          600: '#706858',
          700: '#5a5248',
          800: '#4a443c',
          900: '#3d3832',
          950: '#1e1c19',
        },
        // Aliases for compatibility
        'on-background': '#131B2E',
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-error': '#FFFFFF',
        'on-primary-container': '#EEEFFF',
        'on-secondary-container': '#FFFBFF',
        'on-error-container': '#93000A',
        'inverse-on-surface': '#EEF0FF',
        'inverse-surface': '#283044',
        'inverse-primary': '#B4C5FF',
        'surface-dim': '#D2D9F4',
        'surface-bright': '#FAF8FF',
        'surface-tint': '#0053DB',
        'surface-variant': '#DAE2FD',
        'primary-fixed': '#DBE1FF',
        'primary-fixed-dim': '#B4C5FF',
        'secondary-fixed': '#EADDFF',
        'secondary-fixed-dim': '#D2BBFF',
        'tertiary-fixed': '#6FFBBE',
        'tertiary-fixed-dim': '#4EDEA3',
        'on-primary-fixed': '#00174B',
        'on-primary-fixed-variant': '#003EA8',
        'on-secondary-fixed': '#25005A',
        'on-secondary-fixed-variant': '#5A00C6',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'tertiary-container': '#007D55',
        'on-tertiary-container': '#BDFFDB',
        'error-container': '#FFDAD6',
        'surface-container-highest': '#DAE2FD',
      },
      spacing: {
        'sidebar-width': '260px',
        'container-max': '1440px',
        '2xl': '48px',
        lg: '24px',
        md: '16px',
        sm: '8px',
        xs: '4px',
        gutter: '24px',
        xl: '32px',
        base: '4px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'headline-xl': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;